version: '3.8'

services:
  items-service:
    build:
      context: ./items
    ports:
      - "5001:5001"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://ip-address-otel-collector:4317
      - OTEL_SERVICE_NAME=items
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_LOGS_EXPORTER=otlp

  cart-service:
    build:
      context: ./cart
    ports:
      - "5002:5002"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://ip-address-otel-collector:4317
      - OTEL_SERVICE_NAME=cart
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_LOGS_EXPORTER=otlp

  payment-service:
    build:
      context: ./payment
    ports:
      - "5003:5003"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://ip-address-otel-collector5:4317
      - OTEL_SERVICE_NAME=payment
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_LOGS_EXPORTER=otlp
  # notification-service:
  #   build:
  #     context: ./notify
  #   ports:
  #     - "5004:5004"
  #   environment:
  #     - OTEL_EXPORTER_OTLP_ENDPOINT=http://ip-address-otel-collector:4317
  #     - OTEL_SERVICE_NAME=notification
  #     - OTEL_EXPORTER_OTLP_INSECURE=true
  #     - OTEL_LOGS_EXPORTER=otlp
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  
